// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVx6A0UDuicrNRtuOaJylFgxNTg2QZHM',
    appId: '1:469010978794:web:a7f3582ae579b9fc1e0493',
    messagingSenderId: '469010978794',
    projectId: 'snoreastra',
    authDomain: 'snoreastra.firebaseapp.com',
    storageBucket: 'snoreastra.firebasestorage.app',
    measurementId: 'G-XYEFY2F675',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_XZMuF7Feexi38qvtvNo92OWdb88lso0',
    appId: '1:469010978794:android:775070c4d7db47f91e0493',
    messagingSenderId: '469010978794',
    projectId: 'snoreastra',
    storageBucket: 'snoreastra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtxKu86DjIHQtCIC9uErilh65o-9fJHy8',
    appId: '1:469010978794:ios:6b74123dc940c6bc1e0493',
    messagingSenderId: '469010978794',
    projectId: 'snoreastra',
    storageBucket: 'snoreastra.firebasestorage.app',
    iosBundleId: 'com.snoreclinics.ai',
    iosClientId: '469010978794-jr7536c2s4p8mg0ddsms2ahoq6sk2vfl.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0yQo-D9UPQiyU19sGubOE6s0AvJpDN5I',
    appId: '1:840529050371:ios:36e61a2cfbdec00db84736',
    messagingSenderId: '840529050371',
    projectId: 'snoreclinics-ai',
    storageBucket: 'snoreclinics-ai.firebasestorage.app',
    iosBundleId: 'com.example.sleepAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1CpT15JA-qVrV1BLqi98g5rMoP6MA3HY',
    appId: '1:840529050371:web:2cf306148e9197e5b84736',
    messagingSenderId: '840529050371',
    projectId: 'snoreclinics-ai',
    authDomain: 'snoreclinics-ai.firebaseapp.com',
    storageBucket: 'snoreclinics-ai.firebasestorage.app',
  );

}